### ISSUE TITLE
adder_viz installation issues

### ISSUE THREAD

**Issue by arghasen10** [ac-freeman/adder-codec-rs#83]
I am geeting the following error while trying to install adder-viz in my macOS.

 === Detected OpenCV module header dir at: /usr/local/opt/opencv/include/opencv4/opencv2
  === Found OpenCV version: 4.8.1 in headers located at: /usr/local/opt/opencv/include/opencv4
  === Generating code in: /var/folders/tw/n21pcsbx47n6991w75ctly340000gp/T/cargo-install2rNRjr/release/build/opencv-1248bca4b42eb4aa/out
  === Placing generated bindings into: /var/folders/tw/n21pcsbx47n6991w75ctly340000gp/T/cargo-install2rNRjr/release/build/opencv-1248bca4b42eb4aa/out/opencv
  === Using OpenCV headers from: /usr/local/opt/opencv/include/opencv4
  thread 'main' panicked at /Users/arghasen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clang-sys-1.6.1/src/lib.rs:1735:1:
  a `libclang` shared library is not loaded on this thread
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `adder-viz v0.2.4`, intermediate artifacts can be found at `/var/folders/tw/n21pcsbx47n6991w75ctly340000gp/T/cargo-install2rNRjr`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Can you help me on how to debug this?

**Comment by ac-freeman** [comment]
Thanks for posting your issue! I did a fresh OS install recently and ran into something similar. On Ubuntu, I followed [these](https://apt.llvm.org/#) LLVM installation instructions. On MacOS, you might be able to run `brew install llvm`. Try that and let me know

**Comment by arghasen10** [comment]
Yes I tried the same. But still getting this error on mac. However in Ubuntu it is getting installed.

**Comment by ac-freeman** [comment]
According to the 8th troubleshooting step [here](https://github.com/twistedfall/opencv-rust), it might be that the `clang-runtime` feature needs to be enabled for the OpenCV dependency. Can you make a fork and try adding that feature in the OpenCV import in `Cargo.toml` for adder-viz?

**Comment by ac-freeman** [comment]
Can be circumvented by installing/running without the `open-cv` feature enabled. Eventually, should remove the OpenCV dependency in [EDI](https://crates.io/crates/davis-edi-rs).
